name: Tests

on:
  push:
    branches: [ main ]

env:
  APP_DB_HOST: localhost
  APP_MONGO_DB: clarify
    
jobs:
  test:
    runs-on: ubuntu-latest
    name: Running tests and generate coverage report
    services:
      mongo:
        image: mongo:latest
        env:
          MONGO_INITDB_DATABASE: ${APP_MONGO_DB}
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Run unit tests
        run: mvn test
      - name: generate report codecov
        run: mvn jacoco:report
      - name: Upload coverage
        if: success()
        run: |
          curl -s https://codecov.io/bash | bash
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        shell: bash
      - name: trigger deploy
        if: success()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          repository: ${{ github.repository }}
          event-type: trigger-deploy
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
    
