name: Tests

on:
  push:
    branches: [ main ]

env:
  APP_DB_HOST: localhost
  APP_MONGO_DB: clarify
    
jobs:
  test:
    runs-on: ubuntu-latest
    name: Running tests and generate coverage report
    services:
      postgres:
        image: mongo:latest
        env:
          MONGO_INITDB_DATABASE: ${APP_MONGO_DB}
        ports:
          - 27017:27017
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Run unit tests
        run: mvn test
      - name: generate report codecov
        run: mvn jacoco:report
      - name: Upload coverage
        if: success()
        run: |
          curl -s https://codecov.io/bash | bash
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        shell: bash