name: Test and Coverage report

on:
  push:
    branches: [ main ]

env:
  DB_HOST: localhost
  DB_USERNAME: sats
  DB_PASSWORD: mechanics
    
jobs:
  test:
    runs-on: ubuntu-latest
    name: Running tests and generate coverage report
    needs: compile
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: clarify        
          POSTGRES_PASSWORD: mechanics
          POSTGRES_USER: sats
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Run unit tests
        run: mvn test
      - name: generate report codecov
        run: mvn jacoco:report
      - name: Upload coverage
        if: success()
        run: |
          curl -s https://codecov.io/bash | bash
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        shell: bash